### ISSUE TITLE
server rendering 运行不了

### ISSUE THREAD

**Issue by shenggen1987** [amazeui/amazeui-dingtalk#2]
$ npm start

> amazeui-touch-server-rendering@0.0.0 start /Users/xiexuemei/qjd/work/amazeui-dingtalk/examples/server-rendering
> node bootstrap.js

/Users/xiexuemei/qjd/work/amazeui-dingtalk/js/react/SearchBar.js:156
var brands = Array.from(document.querySelectorAll('.item-title')).map(function (item) {
                        ^

ReferenceError: document is not defined

**Comment by lwxyfer** [comment]
多谢反馈，会尽快处理。不影响正常使用dingtalk的。

**Comment by minwe** [comment]
Fixed via 78cc5ea7a85bc56d1208a92f54c31c944b309195, please retry.
