### ISSUE TITLE
钉钉内项目运行白屏

### ISSUE THREAD

**Issue by zhangzheng159** [amazeui/amazeui-dingtalk#4]
## 测试用例1：
- https://n1k0.github.io/tinysynth/ （基于react.js 版本号：15.3.2）
- 魅族pro6：
    - 原生浏览器：可用
    - 钉钉：白屏
- 华为荣耀8：
    - 原生浏览器：白屏
    - 钉钉：可用
## 测试用例2：
- http://d.paiago.com/?corpid=ding4940d8b848e83b4a&lwfrom=user_dingfriend（Amaze UI for 钉钉）
- 魅族pro6
    - 原生浏览器：可用
    - 钉钉：白屏
- 华为荣耀8：
    - 原生浏览器：白屏
    - 钉钉：可用
## 测试结论： 
- 在有问题的机型下，整个打包的 js 都没有运行 ,也无报错信息出现， 比较难定位到问题。

**Comment by minwe** [comment]
`Array.from` 兼容性问题。

搜索 `Array.from()` 替换成 `[].slice.call()`。
